on:
  - push
  - pull_request
jobs:
  build:
    name: Web site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: nikola build
      - run: sudo gem install html-proofer
      - run: htmlproofer --disable-external --check-html output --url-ignore /feed/
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: find -name "*.yaml" -exec yamllint -s {} \;
      - uses: actions/setup-python@v2
      - run: sudo apt-get install aspell aspell-en
      - run: pip install pyspelling
      - run: pyspelling -c .pyspelling.yaml
      - run: pip install codespell
      - run: find -name "*.md" -exec codespell -L sowe {} \;
